version: '3'
services:
  app:
    build: .
    command: ["sh", "-c", "sleep 10 && ./main"]
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - ./migrations:/migrations
      - pgdata:/var/lib/postgresql/data
    command: >
        bash -c "/usr/local/bin/docker-entrypoint.sh postgres &
                 sleep 10 &&
                 psql -U postgres -d ewallet_db -f /migrations/000004_new_tables.up.sql &&
                 while true; do sleep 1000; done"
      
volumes:
  pgdata:
